---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See CONTRIBUTING.md for installation instructions

ci:
  autoupdate_commit_msg: 'ci(pre-commit): autoupdate hooks'
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args:
          - --branch=main
          - --branch=dev
      - id: end-of-file-fixer
        exclude: ^(.*/)?\.vscode/|\.drawio$
      - id: trailing-whitespace
        exclude: ^(.*/)?\.vscode/|\.drawio$
      - id: check-yaml
        exclude: ^(\.clang-format|(.*/)?\.vscode/)
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude: ^(.*/)?\.vscode/|\.drawio$

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        types_or: [c, c++]

  # Local hooks for project-specific tasks
  - repo: local
    hooks:
      - id: update-file-metadata
        name: Update @date and @copyright fields
        entry: scripts/hooks/update-metadata.sh
        language: script
        types_or: [c, c++]
        pass_filenames: true
