---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.1
    hooks:
      - id: clang-format
        types_or: [c, c++]

  # Local hooks for project-specific tasks
  - repo: local
    hooks:
      - id: update-file-metadata
        name: Update @date and @copyright fields
        entry: scripts/hooks/update-metadata.sh
        language: script
        types_or: [c, c++]
        pass_filenames: true
